### PR TITLE
Export Start Time

### PR DESCRIPTION
**Pull request by Ilink**
This adds start time to exported files. Due to the difficulty/impossibility of parsing the time automatically, a date picker is used. Additionally, the local timezone is included in the export, rather than always using UTC.

### CODE REVIEW

**Comment by mayfield** [comment]
Looks good.  I'll probably move a couple things around so it tries to infer date before asking.

Thanks!

**Comment by Ilink** [comment]
Thanks!

**Comment by mayfield** [comment]
Getting a bit nervous about the timezone stuff.  I will probably revert that for now.

**Comment by Ilink** [comment]
Ok. The 8601 code or the idea of using it at all?

**Comment by mayfield** [comment]
Just using timezone aware ISO8601.

**Comment by mayfield** [comment]
Tweaked to look for `ns.syncActivity.ts` and other trustworthy sources before prompting the user.  And I threw out the old estimated date code and instead have it use your dialog prompt instead.

aa436f4a0274a6195ed8aed1f421517953727054

**Comment by Ilink** [comment]
Nice! I don't quite follow the concerns over ISO8601 since the timezone is part of the standard. But, I understand being cautious.

**Pull request merged**
