### PR TITLE
[feature] Adds option to block winter activities.

### PR DESCRIPTION
**Pull request by mrdmnd**
I got fed up looking at ski activities. Figured I'd extend your awesome extension to hide these, as well.
This code was tested locally and seems to work for me - I may not have exhaustively checked all winter activity types but this is a good first pass, I think. Let me know what you think? Code should be pretty minimal.

### CODE REVIEW

**Comment by mayfield** [comment]
Hi @mrdmnd I'm trying to decide how to proceed with this.  Unbeknownst to you I get frequent requests to filter all sorts of things and activity types.  I updated this issue #108 to reflect the thesis of these requests, which is basically to filter anything and everything.  To keep the UI from exploding with checkboxes it will need to have some sort of multiple select widget (and not the HTML one, which is horrible).

So I don't really have an issue with merging your PR but I wanted to at least communicate that I'll probably not being doing a release with just this change in it.  I'm also slammed with Sauce for Zwift work at the moment so Sauce for Strava is lower priority until I get to MVP with it.

In the off chance that you're interested in taking a swag at #108 I'd be forever in your debt but I wouldn't outright ask for that.  Anyway, let me know your thoughts.

**Comment by mrdmnd** [comment]
Yeah no worries, I recognize the struggle of being an open source maintainer :D

No rush on the change-merge here; I'll take a look at #108 and if it's in my wheelhouse I'll give it a stab.

**Comment by mayfield** [comment]
Since strava is breaking feeds for me, I'm spending more time on this and I'm going to do the advanced system.

I've broken ground here: 65f81f709dc490bf93b2a046ecc554a68c819936

I believe your usecase should be covered by this @mrdmnd

**Comment by mrdmnd** [comment]
Thanks for taking a stab! Sorry, life got in the way and I never got a chance to try #108; however, this seems like it'll do the trick.

**Pull request closed without merging**
