### PR TITLE
Fix KudoAll button not working

### PR DESCRIPTION
**Pull request by alfred-zhong**
截屏2023-08-04 15 25 54

Now the KudoAll button not working at all.
Actually no idea about why it happened. And don't know if there's a more elegant way to solve this. But it really works.

### CODE REVIEW

**Comment by mayfield** [comment]
Thanks @alfred-zhong

**Comment by zamwon** [comment]
When release is planned? On safari kudo all still not working

**Comment by mayfield** [comment]
Chrome and firefox releases have been approved.

Safari release will have to wait a bit.  Apple makes my life very difficult for these and I prefer to wait for validation on the other versions first.

**Comment by simonf00** [comment]
Indeed. Looking forward to a Safari fix.

**Pull request merged**
